main = "src/index.ts"
name = "og-image-generator"
compatibility_date = "2024-07-13"
compatibility_flags = ["nodejs_compat"]

[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[[r2_buckets]]
binding = "R2_ASSETS"
bucket_name = "digides-assets-file"
